spring:
  application:
    name: spring-cloud-seata-rest
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  scan:
    base-packages: org.lmmarise.seata.web.api.impl.controller
  cloud:
    subscribed-services: spring-cloud-seata-order,spring-cloud-seata-repo