logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

spring:
  datasource:
    username: root
    password: lmmgo
    url: jdbc:mysql://localhost:3306/demo4_account?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    data: classpath:data-mysql.sql
    initialization-mode: always
  application:
    name: spring-cloud-seata-account
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: spring-cloud-seata-account
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: org.lmmarise.seata.account.provider.api.impl