spring:
  datasource:
    username: root
    password: lmmgo
    url: jdbc:mysql://localhost:3306/demo4_repo?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    data: classpath:data-mysql.sql
    initialization-mode: always
  application:
    name: spring-cloud-seata-repo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

dubbo:
  application:
    name: spring-cloud-seata-repo
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: org.lmmarise.seata.repo.api.impl